redditclone/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='login'),
    url(r'^logout/', views.logoutview, name='logout'),
]

redditclone/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    url(r'^user/(?P<fk>[0-9]+)', views.userposts, name='userposts'),
]

redditclone/redditclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name="home"),
]

redditclone/accounts/models.py
from django.db import models

# Create your models here.

redditclone/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    votes_total = models.IntegerField(default=1)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

redditclone/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error':'Username has alredy been taken'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error':'Passwords didn\'t match'})
    else:
        return render(request, 'accounts/signup.html')

def loginview(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error':'The Username and Password didn\'t match'})
    else:
        return render(request, 'accounts/login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

redditclone/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
from django.contrib.auth.models import User
# Create your views here.

@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error':'ERROR: You must include a title and a URL to create a post.'})
    else:
        return render(request, 'posts/create.html')

def home(request):
    posts = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html', {'posts':posts})

def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home')

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect('home')

def userposts(request, fk):
    posts = Post.objects.filter(author__id=fk).order_by('-votes_total')
    author = User.objects.get(pk=fk)
    return render(request, 'posts/userposts.html', {'posts':posts, 'author':author})

redditclone/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<h1>Login</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form method="POST" action="{% url 'accounts:login' %}">
  {% csrf_token %}

  {% if request.GET.next %}
  <input type="hidden" name="next" value={{ request.GET.next }} />
  {% endif %}

  Username:
  <br />
  <input type="text" name="username" />
  <br />
  Password:
  <br />
  <input type="password" name="password" />
  <br />
  <br />
  <input class="btn btn-primary" type="submit" value="Login">
</form>

{% endblock %}

redditclone/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign Up!</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form method="POST" action="{% url 'accounts:signup' %}">
  {% csrf_token %}
  Username:
  <br />
  <input type="text" name="username" />
  <br />
  Password:
  <br />
  <input type="password" name="password1" />
  <br />
  Confirm Password:
  <br />
  <input type="password" name="password2" />
  <br />
  <br />
  <input class="btn btn-primary" type="submit" value="Sign Up!">
</form>

{% endblock %}

redditclone/posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h1>New Post</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form method="POST" action="{% url 'posts:create' %}">
  {% csrf_token %}

  Title:
  <br />
  <input type="text" name="title" />
  <br />
  URL:
  <br />
  <input type="text" name="url" />
  <br />
  <br />
  <input class="btn btn-primary" type="submit" value="Post">
</form>

{% endblock %}

redditclone/posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}
<h1>The homepage</h1>
<a class="btn btn-primary" href="{% url 'posts:create' %}">New Post</a>

<br/>
<br/>

{% for post in posts.all %}

<table>
  <tr>
    <td style="padding-right: 20px;"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a><br/>{{ post.votes_total }}<br/><a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a></td>
    <td><a href="{{ post.url }}">{{ post.title }}</a><br/>{{ post.pub_date_pretty }} by <a href="{% url 'posts:userposts' post.author.id %}">{{ post.author.username }}</a></td>
  </tr>
</table>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
  {% csrf_token %}
  <input type="hidden">
</form>

<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
 {% csrf_token %}
 <input type="hidden">
 </form>

{% endfor %}

{% endblock %}

redditclone/posts/templates/posts/userposts.html
{% extends 'base.html' %}

{% block content %}
<h1>All Posts by {{ author.username }}</h1>
<br/>

{% for post in posts.all %}

<table>
  <tr>
    <td style="padding-right: 20px;"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a><br/>{{ post.votes_total }}<br/><a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a></td>
    <td><a href="{{ post.url }}">{{ post.title }}</a><br/>{{ post.pub_date_pretty }} by <a href="{% url 'posts:userposts' post.author.id %}">{{ post.author.username }}</a></td>
  </tr>
</table>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
  {% csrf_token %}
  <input type="hidden">
</form>

<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
 {% csrf_token %}
 <input type="hidden">
 </form>

{% endfor %}

{% endblock %}

redditclone/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Reddit Clone</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Reddit Clone</a>
        </div>
        <div class="collapse navbar-collapse" id="mynav">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="#" onClick="document.getElementById('logout').submit()">Logout</a></li>
            <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
              {% csrf_token %}
              <input type="hidden">
            </form>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>